   - name: Create a directory
     file:
       path: '{{ dest_dir }}'
       state: directory
       mode: '0755'



   - name: Unzip on remote
     unarchive: 
      src: '{{ source_dir }}{{ source_list.source }}'
      dest: '{{ dest_dir }}'


   - name: Copy file with owner and permissions
     copy:
       src: '{{ source_dir }}{{ executable }}'
       dest: '{{ dest_dir }}'
       mode: '0755'


   - name: Change the working directory to and run generic tibcoinstall .
     command: ' {{ executable_command }} -silent  {{ silent | join(" ")}}'
     args:
      chdir: '{{ dest_dir }}'
     when: source_list.silent_file=='NONE'
 
   - name:  generate silent file 
     template: "src={{source_list.silent_file}} dest={{dest_dir}}/{{source_list.name}}.silent mode=0644"
     when: source_list.silent_file != 'NONE'

   - name: Change the working directory to and run silent tibcoinstall .
     command: '{{ executable_command }} -silent  -V responseFile="{{ source_list.name }}.silent"'
     args:
      chdir: '{{ dest_dir }}'
     when: source_list.silent_file!='NONE' 


   - name: Clean path
     file:
       state: absent
       path: "{{ dest_dir }}/"


   - name: Create a directory
     file:
       path: '{{ dest_dir }}'
       state: directory
       mode: '0755'


